apiVersion: v1
kind: Service
metadata:
  name: appartement
  namespace: default

spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

  selector:
    app: appartement
  type: ClusterIP
